import Head from "next/head";
import Link from "next/link";
import React from "react";

const About = () => {
  return (
    <>
      <Head>
        <title>Next App | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Link href={"/"}>home</Link>
      </div>
    </>
  );
};

export default About;
