import Layout from "@/layouts/layout";
import { Button } from "@mui/material";
import Head from "next/head";
import Link from "next/link";

const Home = () => {
  return (
    <Layout>
      <Head>
        <title>Next App | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Home
      </main>
    </Layout>
  );
};

export default Home;
